on:
  workflow_call:
    inputs:

      upgrade-policy:
        description: "Node.js version upgrade policy. Allowed values: `lts` (default), `lts/strict`, `all`."
        default: lts
        required: false
        type: string
      runs-on:
        description: "Comma separated list of runner labels (note: not YAML!), see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on."
        default: "ubuntu-latest"
        required: false
        type: string

      post-checkout-steps:
        description: "Steps to execute after checkout (i.e. before installing dependencies)"
        required: false
        type: string

      post-install-steps:
        description: "Steps to execute after installing dependencies (i.e. before running tests)"
        required: false
        type: string

      post-test-steps:
        description: "Steps to execute after the tests complete"
        required: false
        type: string

      strategy-fail-fast:
        description: "Set to true to cancel the workflow as soon as the first matrix combo fails. Note: default here is different than the Github Actions default."
        default: false
        required: false
        type: boolean

      strategy-max-parallel:
        description: "The maximum number of matrix jobs that can run simultaneously."
        default: 0
        required: false
        type: number

      test-command:
        description: "Command to run instead of `npm test` (e.g. for coverage)."
        default: npm test
        required: false
        type: string

jobs:

  prepare-node-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      runs-on: ${{ steps.set-matrix.outputs.runs-on }}
      lts-latest: ${{ steps.set-matrix.outputs.lts-latest }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare the matrix
      uses: dominykas/pkgjs-action/.github/actions/prepare-node-test-matrix-action@main
      id: set-matrix
      with:
        upgrade-policy: ${{ inputs.upgrade-policy }}
        runs-on: ${{ inputs.runs-on }}

  test:
    needs: prepare-node-matrix

    strategy:
      fail-fast: ${{ inputs.strategy-fail-fast }}
      max-parallel: ${{ inputs.strategy-max-parallel }}
      matrix:
        node-version: ${{ fromJson(needs.prepare-node-matrix.outputs.matrix) }}
        runs-on: ${{ fromJson(needs.prepare-node-matrix.outputs.runs-on) }}

    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare post-checkout steps
      if: ${{ inputs.post-checkout-steps }}
      uses: dominykas/pkgjs-action/.github/actions/prepare-dynamic-steps@main
      with:
        steps: ${{ inputs.post-checkout-steps }}
        path: post-checkout-steps

    - name: Prepare post-install steps
      if: ${{ inputs.post-install-steps }}
      uses: dominykas/pkgjs-action/.github/actions/prepare-dynamic-steps@main
      with:
        steps: ${{ inputs.post-install-steps }}
        path: post-install-steps

    - name: Prepare post-test steps
      if: ${{ inputs.post-test-steps }}
      uses: dominykas/pkgjs-action/.github/actions/prepare-dynamic-steps@main
      with:
        steps: ${{ inputs.post-test-steps }}
        path: post-test-steps

    - name: Setup Node.js@${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run post-checkout steps
      if: ${{ inputs.post-checkout-steps }}
      uses: ./.github/tmp/post-checkout-steps


    - name: Install dependencies
      run: npm install
      env:
        MATRIX_NODE_VERSION: ${{ matrix.node-version }}
        NODE_LTS_LATEST: ${{ needs.prepare-node-matrix.outputs.lts-latest }}

    - name: Run post-install steps
      if: ${{ inputs.post-install-steps }}
      uses: ./.github/tmp/post-install-steps


    - name: Run tests
      run: ${{ inputs.test-command }}
      env:
        MATRIX_NODE_VERSION: ${{ matrix.node-version }}
        NODE_LTS_LATEST: ${{ needs.prepare-node-matrix.outputs.lts-latest }}

    - name: Run post-test steps
      if: ${{ inputs.post-test-steps }}
      uses: ./.github/tmp/post-test-steps
