on:
  workflow_call:
    inputs:
      upgradePolicy:
        description: "Node.js version upgrade policy. Allowed values: `lts` (default), `lts/strict`, `all`."
        default: lts
        required: false
        type: string

jobs:

  prepare-node-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      lts_latest: ${{ steps.set-matrix.outputs.lts_latest }}

    steps:
    - uses: actions/checkout@v2
    - uses: dominykas/pkgjs-action/private-actions/prepare-node-test-matrix-action@main
      id: set-matrix
      with:
        upgradePolicy: ${{ inputs.upgradePolicy }}

  test:
    runs-on: ubuntu-latest
    needs: prepare-node-matrix

    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prepare-node-matrix.outputs.matrix) }}

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
      env:
        MATRIX_NODE_VERSION: ${{ matrix.node-version }}
        NODE_LTS_LATEST: ${{ needs.prepare-node-matrix.outputs.lts_latest }}

    - run: npm test
      env:
        MATRIX_NODE_VERSION: ${{ matrix.node-version }}
        NODE_LTS_LATEST: ${{ needs.prepare-node-matrix.outputs.lts_latest }}
